In [1]:
>>> import pandas as pd
>>> import numpy as np

In [2]:
df=pd.read_csv("C:\\Users\\HP\\Downloads\\amazon_best_sellers_gaming_merchandise_2024.csv")

In [3]:
>>> import numpy as np
>>> from sklearn.linear_model import LinearRegression

In [4]:
df.head(5)

,title,brand,description,stars,reviewsCount,price/currency,price/value,breadCrumbs,asin,url
0,"Do Not Disturb I'm Gaming Socks,Valentines Day...",Kelool,NaN,4.7,926.0,NaN,NaN,"Clothing, Shoes & Jewelry › Novelty & More › C...",B092J1SPX5,https://www.amazon.com/dp/B092J1SPX5
1,Razer Tartarus V2 Gaming Keypad: Mecha-Membran...,Razer,The Razer Tartarus V2 provides endless command...,4.4,15386.0,$,77.00,Video Games › PC › Accessories › Controllers ›...,B07754PYFK,https://www.amazon.com/dp/B07754PYFK
2,"Neon Gaming Decor for Boys Room Wooden, Neon G...",Simimi art,NaN,4.4,25.0,$,9.99,Baby Products › Nursery › Décor › Wall Décor ›...,B0CBCBQG4V,https://www.amazon.com/dp/B0CBCBQG4V
3,I Paused My Game to Be Here Video Gamer Mens R...,Feelin Good Tees,The best part is when you pull this shirt over...,4.7,18918.0,NaN,NaN,NaN,B07PH1R6X3,https://www.amazon.com/dp/B07PH1R6X3
4,Neon Sign King Boo The Ghost Face LED Neon Lig...,JOSEBRU,NaN,4.7,536.0,$,39.99,Tools & Home Improvement › Lighting & Ceiling ...,B09Q89FL7G,https://www.amazon.com/dp/B09Q89FL7G


In [5]:
>>> x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
>>> y = np.array([5, 20, 14, 32, 22, 38])

In [6]:
>>> x
array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

>>> y
array([ 5, 20, 14, 32, 22, 38])

NameError: name 'array' is not defined

In [7]:
x = np.array([[5], [15], [25], [35], [45], [55]])
y = np.array([5, 20, 14, 32, 22, 38])

print(x)
print(y)


[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]


In [8]:
>>> model = LinearRegression()

In [9]:
>>> model.fit(x, y)
LinearRegression()

LinearRegression()

In [10]:
>>> model = LinearRegression().fit(x, y)

In [60]:
>>> r_sq = model.score(x, y)
>>> print(f"coefficient of determination: {r_sq}")
coefficient of determination: 0.7158756137479542

SyntaxError: invalid syntax (1550001903.py, line 3)

In [12]:
from sklearn.metrics import r2_score

# Assuming your coefficient of determination value is stored in a variable named 'r2'
r2 = 0.7158756137479542

print("Coefficient of determination:", r2)


Coefficient of determination: 0.7158756137479542


In [13]:
>>> print(f"intercept: {model.intercept_}")
intercept: 5.633333333333329

>>> print(f"slope: {model.coef_}")
slope: [0.54]

intercept: 5.633333333333329
slope: [0.54]


In [14]:
>>> new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
>>> print(f"intercept: {new_model.intercept_}")
intercept: [5.63333333]

>>> print(f"slope: {new_model.coef_}")
slope: [[0.54]]

intercept: [5.63333333]
slope: [[0.54]]


In [16]:
>>> y_pred = model.predict(x)
>>> print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [17]:
>>> y_pred = model.intercept_ + model.coef_ * x
>>> print(f"predicted response:\n{y_pred}")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [19]:
>>> x_new = np.arange(5).reshape((-1, 1))
>>> x_new
>>> y_new = model.predict(x_new)
>>> y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

In [20]:
>>> import numpy as np
>>> from sklearn.linear_model import LinearRegression

>>> x = [
...   [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
... ]
>>> y = [4, 5, 20, 14, 32, 22, 38, 43]
>>> x, y = np.array(x), np.array(y)

In [22]:
>>> x

>>> y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [23]:
>>> model = LinearRegression().fit(x, y)

In [25]:
>>> r_sq = model.score(x, y)
>>> print(f"coefficient of determination: {r_sq}")
>>> print(f"intercept: {model.intercept_}")
>>> print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8615939258756775
intercept: 5.52257927519819
coefficients: [0.44706965 0.25502548]


In [26]:
>>> y_pred = model.predict(x)
>>> print(f"predicted response:\n{y_pred}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [27]:
>>> x_new = np.arange(10).reshape((-1, 2))
>>> x_new

>>> y_new = model.predict(x_new)
>>> y_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])

In [28]:
>>> import numpy as np
>>> from sklearn.linear_model import LinearRegression
>>> from sklearn.preprocessing import PolynomialFeatures

In [29]:
>>> x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
>>> y = np.array([15, 11, 2, 8, 25, 32])

In [30]:
>>> transformer = PolynomialFeatures(degree=2, include_bias=False)

In [31]:
>>> transformer.fit(x)
PolynomialFeatures(include_bias=False)

PolynomialFeatures(include_bias=False)

In [32]:
>>> x_ = transformer.transform(x)

In [33]:
>>> x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [36]:
>>> x_

array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])

In [37]:
>>> model = LinearRegression().fit(x_, y)

In [38]:
>>> r_sq = model.score(x_, y)
>>> print(f"coefficient of determination: {r_sq}")

>>> print(f"intercept: {model.intercept_}")

>>> print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8908516262498564
intercept: 21.372321428571425
coefficients: [-1.32357143  0.02839286]


In [39]:
>>> x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [40]:
>>> x_

array([[1.000e+00, 5.000e+00, 2.500e+01],
       [1.000e+00, 1.500e+01, 2.250e+02],
       [1.000e+00, 2.500e+01, 6.250e+02],
       [1.000e+00, 3.500e+01, 1.225e+03],
       [1.000e+00, 4.500e+01, 2.025e+03],
       [1.000e+00, 5.500e+01, 3.025e+03]])

In [41]:
>>> model = LinearRegression(fit_intercept=False).fit(x_, y)

In [43]:
>>> r_sq = model.score(x_, y)
>>> print(f"coefficient of determination: {r_sq}")
>>> print(f"intercept: {model.intercept_}")

>>> print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8908516262498565
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]


In [44]:
>>> y_pred = model.predict(x_)
>>> print(f"predicted response:\n{y_pred}")

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


In [45]:
>>> # Step 1: Import packages and classes
>>> import numpy as np
>>> from sklearn.linear_model import LinearRegression
>>> from sklearn.preprocessing import PolynomialFeatures

>>> # Step 2a: Provide data
>>> x = [
...   [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
... ]
>>> y = [4, 5, 20, 14, 32, 22, 38, 43]
>>> x, y = np.array(x), np.array(y)

>>> # Step 2b: Transform input data
>>> x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

>>> # Step 3: Create a model and fit it
>>> model = LinearRegression().fit(x_, y)

>>> # Step 4: Get results
>>> r_sq = model.score(x_, y)
>>> intercept, coefficients = model.intercept_, model.coef_

>>> # Step 5: Predict response
>>> y_pred = model.predict(x_)

In [46]:
>>> print(f"coefficient of determination: {r_sq}")
>>> print(f"intercept: {intercept}")

>>> print(f"coefficients:\n{coefficients}")
>>> print(f"predicted response:\n{y_pred}")

coefficient of determination: 0.9453701449127822
intercept: 0.8430556452395734
coefficients:
[ 2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]
predicted response:
[ 0.54047408 11.36340283 16.07809622 15.79139    29.73858619 23.50834636
 39.05631386 41.92339046]


In [47]:
>>> import numpy as np
>>> import statsmodels.api as sm

In [48]:
>>> x = [
...   [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
... ]
>>> y = [4, 5, 20, 14, 32, 22, 38, 43]
>>> x, y = np.array(x), np.array(y)

In [49]:
>>> x = sm.add_constant(x)

In [50]:
>>> x

>>> y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [51]:
>>> model = sm.OLS(y, x)

In [52]:
>>> results = model.fit()

In [54]:
>>> print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Mon, 04 Mar 2024   Prob (F-statistic):            0.00713
Time:                        14:30:04   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

C:\ProgramData\anaconda3\Lib\site-packages\scipy\stats\_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [55]:
>>> print(f"coefficient of determination: {results.rsquared}")

>>> print(f"adjusted coefficient of determination: {results.rsquared_adj}")

>>> print(f"regression coefficients: {results.params}")

coefficient of determination: 0.8615939258756777
adjusted coefficient of determination: 0.8062314962259488
regression coefficients: [5.52257928 0.44706965 0.25502548]


In [56]:
>>> print(f"predicted response:\n{results.fittedvalues}")

>>> print(f"predicted response:\n{results.predict(x)}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]
predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [58]:
>>> x_new = sm.add_constant(np.arange(10).reshape((-1, 2)))
>>> x_new

>>> y_new = results.predict(x_new)
>>> y_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])